### ISSUE TITLE
Reset button on backend project search triggers exception.

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#975] opened 2018-04-16 20:59 UTC
The `Reset Search` button for the project search bar on the UMP instance is unresponsive. When you click it, the bar remains populated with the input from the last search and the results remain the same.

**Comment by zdavis** [comment] 2018-04-16 21:00
Does this only happen on the search results page?

**Comment by tsmyre** [comment] 2018-04-16 21:02
The backend landing page is where I'm experiencing it:

![screen shot 2018-04-16 at 4 02 00 pm](https://user-images.githubusercontent.com/25825222/38834943-8623bdc4-418f-11e8-9b84-619d6f0e51f5.png)

**Comment by zdavis** [comment] 2018-04-16 21:03
Thanks. I see the problem now.

**Comment by zdavis** [comment] 2018-04-16 21:14
Duplicate of https://github.com/ManifoldScholar/manifold/issues/922, which is fixed in Master. Closing.

**Closed by zdavis** 2018-04-16 21:14 UTC
Labels: bug
