### ISSUE TITLE
Closing out resource view within a text returns user to top of chapter

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#1411] opened 2018-09-21 13:41 UTC
When one is reading a Manifold text and is midway down the page, and when one then opens a resource, the resource modal pops up. When that modal is closed, the reader is returned not to the place on the page where she was previously but rather to the very top of the page, which is confusing as it makes the user lose her place in the text.

## Expected Behavior

When the modal is closed, the reader should be returned to the place in the text where she was before she opened the modal

## Current Behavior

When the modal is closed, the reader is returned to the top of the page

## Steps to Reproduce

1. Go to a Manifold text with resources placed in the text
2. scroll down and find the resource
3. open resource modal
4. close resource modal
5. Notice that the view is returned to the top of the page upon modal close

**Comment by zdavis** [comment] 2018-09-21 14:42
Dupe of #823. Closing.

**Closed by zdavis** 2018-09-21 14:42 UTC
