### ISSUE TITLE
Failed ePub ingestion

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#829] opened 2018-03-07 14:56 UTC
Following the fix in https://github.com/ManifoldScholar/manifold/issues/821 , I tried to reingest the ePub, but I ran into the following issue:

Updated text_section: "The Sound of Silence"
Updated text_section: "Glossary"
Attempting to save the text
Spine has 86 items
Found text starting section: "ch1"
Looking for TOC structure
Looking for page list structure
Looking for landmark structure
Processing failed: undefined method `orange' for "Unable to update text section \"The Sound of Silence\"":String

**Comment by mkgold** [comment] 2018-03-09 21:31
Just tried again with this file and ran into the same issue. @zdavis -- any thoughts?

**Comment by zdavis** [comment] 2018-03-09 21:44
@SMaxOwok please investigate and help resolve.

**Comment by SMaxOwok** [comment] 2018-03-09 21:45
@mkgold where did you see this happen?  I tried again, reingesting, since the fix and wasn't able to replicate the issue.

**Comment by zdavis** [comment] 2018-03-09 22:20
Probably on the CUNY instance. I'm thinking maybe the release didn't go as intended. Double checking Jenkins log.

**Comment by zdavis** [comment] 2018-03-09 22:21
In theory, the CUNY instance is at a218270, which is the head of the v0.4.x branch. Is it your sense that this issue is fixed there?

**Comment by mkgold** [comment] 2018-03-09 22:22
Yes -- this was on the CUNY install

**Comment by zdavis** [comment] 2018-03-09 22:51
We can reproduce on the CUNY instance, but not locally (yet). We're working on it.

**Comment by zdavis** [comment] 2018-03-13 23:12
Will be fixed in 0.5.0. It's kind of an edge case, so I'm not going to include this in the 0.4.x branch.

**Comment by zdavis** [comment] 2018-03-13 23:13
Er, yes I am, because that's where the PR went. D'oh. Merging to master.

**Closed by zdavis** 2018-03-13 23:12 UTC
Labels: bug, has pull request
