### ISSUE TITLE
Private RG annotations are included in notification emails.

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#2933] opened 2021-02-03 16:22 UTC
I just received an email about an annotation in _Debates in the Digital Humanities_. When I click on the "View Annotation" link, I'm brought to the text where the annotation was placed, but the annotation shelf itself doesn't open to show the annotation. I don't think this is expected behavior. I've attached a copy of the email notification here.

[An annotation has been made on Debates in the Digital Humanities.pdf](https://github.com/ManifoldScholar/manifold/files/5919922/An.annotation.has.been.made.on.Debates.in.the.Digital.Humanities.pdf)

**Comment by zdavis** [comment] 2021-02-03 16:31
@ManifoldScholar/cast-iron-coding would you mind updating the issue with the URL that the link goes to—I can't seem to get it from the PDF.

**Comment by mkgold** [comment] 2021-02-03 17:15
Sure -- [here it is](https://u5908462.ct.sendgrid.net/ls/click?upn=RsDy9Qx8q-2BYxG-2FYd-2Fcm2cCjwd423eEFeA9EQp5jnSZj-2FrueT4IIOMrJ-2F1o8EEhxaZteSXyaaS6qVJkxNzL6oh1LZfce-2B04QAMIDSr-2F9cgsdGks85ye-2FxnMPsvm7pN63lixWyiqJclNJok18SLbhHmvJyrOKLG3J2AqF8taIu5oBQHIsgAyKzWU-2F9l43BAwZeK7CYUIR67cDWSkWjnX1uyalnrtEp5LY85WxSafnNnVlsXOoG5LwHSgrj1j7cuUQWWiH2_2yZAsJ88F-2FjjXjwe-2BpXCKXvQDP8viOl6UAlyjaCbzWljo1Ldob7qEgsK-2FOKJK3jgPMfWYUS66uXtkCcOwf5k7V5DBIDcFJVGTVxBdcLhJdAidJaYM-2BqqOqMdLzM7iUVFnDZBM64CQ6twm5DiKHwcSA3pU4903-2FP6UITQRAAe-2BWlx7-2Fmk-2FOWZ7jpZteqgaXypDmU7o6gj6jo2kxr0yiNoIKx0Ujeu9W8eEwJWv9W32zw-3D).

**Comment by zdavis** [comment] 2021-04-08 14:34
Thank you for taking the time to report this bug. We've reviewed the issue and agree that this should be fixed. We’re adding a “planned” label to indicate that we consider this bug as part of our current work plan.

_This was an automated message, but please don't hesitate to reply. Our team watches these issues closely and will respond as soon as we're able to!_

**Comment by zdavis** [comment] 2021-04-08 16:44
Matt, thanks again for reporting this. I've investigated, and the issue is more with notification than with linking to annotations in the reader. I'm going to update the issue title to accurately reflect the problem.

**Closed** 2021-04-08 17:40 UTC
Labels: Status: In Progress, Status: Planned, Type: Bug
