### ISSUE TITLE
Long text titles may clip through event card

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#430] opened 2017-07-11 19:57 UTC
![screen shot 2017-07-11 at 12 57 08 pm](https://user-images.githubusercontent.com/8389445/28087788-8860998c-6638-11e7-8e09-92e67ed5cebd.png)

**Comment by zdavis** [comment] 2017-07-11 23:28
Closing because this is a duplicate of #401.

**Closed by zdavis** 2017-07-11 23:28 UTC
Labels: bug
