### ISSUE TITLE
Include direct links to comments in digest and flag email notifications

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#2829] opened 2020-08-21 21:36 UTC
I've been receiving notifications of new comments in a few ways. For some annotations, I receive a message with the subject line "An annotation has been made on [text title]." These emails feature the full annotation and include a link that says View Annotation. Clicking on that link brings on directly to the annotation modal screen, where one can see the annotation.

There are two other types of email notifications I receive that do not include such direct links -- digest emails and flagged annotations. 

1. The digest emails come with the subject line "Your Daily Manifold Summary" and include, in the body, something like 

Annotations Added Today:
"social bookmarking" on Being a Scholar in the Digital Era

In this case, I love love a link that I can follow to view this annotation

2. The flagged annotation email notification similarly does not provide a direct link to the annotation, and this is problematic, as it can be hard to find the comment that was flagged, and the who point of flagging it should be so that admins can go in and look at the annotations. I think we should include a direct link there, too.

**Comment by zdavis** [comment] 2020-10-09 23:05
@bot planned

**Comment by zdavis** [comment] 2020-10-09 23:05
Thank you for taking the time to open this feature request. The Manifold team reviewed this issue during our bi-weekly meeting and the consensus is that this feature makes sense and is in keeping with our overall vision for the platform. Moreover, we see this request as a viable candidate for development under our current available funding. We’re adding a “planned” label to this feature to indicate that we plan on completing it within our current funding cycle.

_This was an automated message, but please don't hesitate to reply. Our team watches these issues closely and will respond as soon as we're able to!_

**Comment by zdavis** [comment] 2021-04-14 19:09
I just did a test of the flagged annotation email, and it's definitely including a link to the annotation. Perhaps this was addressed outside this issue?

**Comment by zdavis** [comment] 2021-04-14 20:01
Also unable to reproduce the issue in the daily digest. It too renders a link to the specific annotation.

**Comment by zdavis** [comment] 2021-04-14 20:03
I'm closing this, Matt, because I can't reproduce the issue. You have a couple of options here:

- Next time you get one of these emails, check again. There's definitely a link (at least in master) that ends with something like `#annotation-a620e582-c896-49fb-bc0b-e2cceabc3d4a`, which is a link to a specific annotation. 
- Maybe we fixed this in v6, although I don't remember doing it—see if it's still an issue after we update your instances and reopen if it is.
- Feel free to open a new issue for your other request around adding explanation to flags.

**Closed by zdavis** 2021-04-14 20:03 UTC
Labels: Status: Planned, Type: Enhancement
