### ISSUE TITLE
Closing resource modal loses place in reader

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2156] opened 2019-04-25 23:26 UTC
In this [text](https://manifold.umn.edu/read/df831529-6030-48f1-8481-c26d65d6e79a/section/f0b7aa36-06d6-4566-86da-4728c360ef75), when I close any of the resource modals (save for the second one, the library interior), the reader returns to the top of the section instead of keeping me where I clicked the resource.

**Comment by zdavis** [comment] 2020-02-12 21:07
@bot bug

**Comment by zdavis** [comment] 2020-02-12 21:07
Thank you for taking the time to report this bug. We've reviewed the issue and agree that this should be fixed. We’re adding a “planned” label to indicate that we consider this bug as part of our current work plan.

_This was an automated message, but please don't hesitate to reply. Our team watches these issues closely and will respond as soon as we're able to!_

**Comment by zdavis** [comment] 2021-04-08 00:35
This appears to have been fixed, @tsmyre. I'm not able to reproduce it any more. Feel free to reopen if you can.

**Closed by zdavis** 2021-04-08 00:35 UTC
Labels: Priority: Medium, Status: Planned, Type: Bug
