### ISSUE TITLE
Order of projects in collections

### ISSUE THREAD

**Issue by BethFuget** [ManifoldScholar/manifold#2146] opened 2019-04-13 02:50 UTC
We can order projects in collections in various ways - alphabetically, by pub date, etc. - and they show up in this order on the homepage but not on the "See the Full Collection" page. Can this be set so the default is for projects to show up in the selected order on this page too? Thanks!

**Comment by SMaxOwok** [comment] 2019-04-23 22:27
This could probably be considered a bug... Default order for a project collection should be its collection order.

**Comment by zdavis** [comment] 2019-05-22 21:24
@BethFuget — thanks for this bug report! We have a fix for this working through the pull request pipeline, and it should be addressed in version 3.1 of Manifold.

**Closed** 2019-05-22 21:29 UTC
Labels: bug, has pull request

**Comment by BethFuget** [comment] 2019-07-12 19:58
Sorry for this very basic question, but how do we find out what version of Manifold we're running? Are we still on 3.0, or 3.1 now? I'm wondering because this collection order problem has been mostly but not entirely fixed, and I don't know if it's still in process or was already addressed but there's a pending glitch to fix. Thanks!

**Comment by BethFuget** [comment] 2019-07-12 19:59
Also, if I comment on a closed issue, will anyone ever see it?

**Comment by zdavis** [comment] 2019-07-12 20:00
Yes, because I'm ALWAYS WATCHING! :)

**Comment by BethFuget** [comment] 2019-07-12 20:02
You are!!!

**Comment by zdavis** [comment] 2019-07-12 20:05
Also, to answer your question—I keep you and all the other pilots on the  most recent stable bugfix branch, which is currently https://github.com/ManifoldScholar/manifold/tree/v3.0.x.

The fix for this issue was merged into the master branch, which means it would be included in the next release that's not a bugfix release (likely 3.1). That said, if you really don't want to wait for that release, you ask us to cherry-pick the bug into the v3.0.x branch and push it out to your instance. If it's a small fix, which this is, that's generally a fairly simple process.

Zach

**Comment by BethFuget** [comment] 2019-07-12 20:10
Thanks, Zach! I can wait. It's just that I noticed that the problem was mostly but not entirely fixed, so I didn't know if that meant that the work was still in process or that someone addressed it but missed something. And that's why I was wondering what version we're on.
