### ISSUE TITLE
Text creation events are appearing twice

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1415] opened 2018-09-21 17:45 UTC
![screen shot 2018-09-21 at 10 44 43 am](https://user-images.githubusercontent.com/8389445/45897245-6fe23680-bd8b-11e8-9178-841aaa9d4221.png)

**Comment by SMaxOwok** [comment] 2018-09-21 18:12
We create/update a text's `text_added` event whenever a text is saved (`after_create`, `after_update`).  The text is saved a handful of times during the ingestion process.

I believe that this was a race condition issue of the `Factory::Event#create` running twice for the same subject and not finding an existing event.
```
      event = ::Event.find_or_create_by(
        subject: subject,
        event_type: event_type,
        project: subject_project(subject)
      )
```

I'm thinking maybe two separate callbacks for the text, one for create and one for update.  The update callback would abort if there is not an existing `text_creation_event`.

Thoughts @zdavis, @scryptmouse?

**Comment by SMaxOwok** [comment] 2018-09-21 18:13
Also worth noting that the text callbacks happening on create and update to keep the event synced with the subject (title, subtitle, etc.).  This is the only model we do this for, but for other event types that include the subject's info, we should probably be updating the events on update as well.

**Comment by zdavis** [comment] 2018-09-21 18:16
Is this bug only surfacing after you wrapped things in a transaction? Is it easily reproducible, or does it only happen sometimes.

I don't understand why we would do this on after_create or after_update. Why wouldn't we _only_ do it in `after_commit :do_something, on[:create]`. Even if we do want it in both, it should be via `after_commit :do_something, on[:create, :update]`.

**Comment by SMaxOwok** [comment] 2018-09-21 18:20
Sorry, it is `after_commit :trigger_event_creation, on: [:create, :update]`, I misspoke.

I haven't been able to replicate yet and had @tsmyre go through the exact steps again on the instance while I watched the logs.  All I saw was the event job run a couple times, but the bug did not appear.

**Comment by zdavis** [comment] 2018-09-21 18:27
I wonder if we can enforce uniqueness here at the DB level?

**Comment by SMaxOwok** [comment] 2018-09-21 18:29
Maybe that `event_type` is unique scoped to `subject`?

**Comment by zdavis** [comment] 2018-10-25 16:35
@tsmyre We're unable to reproduce this, which doesn't mean it's not an issue, just that we don't have a good solution at this time. I'm going to close this bug for now, but we should reopen it if this issue persists, or if you see it again.

**Closed by zdavis** 2018-10-25 16:35 UTC
Labels: bug, confirmed
