### ISSUE TITLE
Consider allowing dynamic components in comments and texts

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1778] opened 2019-01-16 21:14 UTC
We've talked in person and on Slack about allowing markdown, embeds, and perhaps dynamic components in annotations, comments, and maybe even in texts. The two repos below have come up specifically, and it may align with the work slated for v4.0. I note them here so we have a record we can easily reference and refer back to.

- [Idyll Toolkit for Interactive Text](https://idyll-lang.org/)
- [Slate Rich-Text Editor](https://docs.slatejs.org/)

**Comment by mkgold** [comment] 2019-01-18 04:34
awesome

**Comment by SMaxOwok** [comment] 2019-01-18 15:53
I believe this is a dupe of #1721, unless there is more functionality included here.

**Comment by tsmyre** [comment] 2019-01-18 16:07
@SMaxOwok It looks like #1727 is also closely aligned. Neither of those mention [Idyll](https://idyll-lang.org/), however.

**Comment by zdavis** [comment] 2019-04-04 15:48
Given our other priorities, I don't see us tackling the Idyll integration in the near-term. I think this should be flagged as funding needed and closed for the time being, esp. because we're already addressing the RTE aspect of this in #1721, which is more actionable at this time.

**Closed** 2019-04-04 15:49 UTC
Labels: feature, funding needed
