### ISSUE TITLE
Feature Request: Import multiple google docs as a single text

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#1070] opened 2018-05-18 20:42 UTC
[This has been significantly revised from Matt's initial post to reflect subsequent discussion. -ZD]

## Feature Description
This feature would allow text creators to combine multiple google docs into a single Manifold text. The ingestion process would be modified to support a new type of ingestion called "Google Docs Manifest" (working title, exact nomenclature TBD). During ingestion, the user would import a YML manifest that expressed the text structure. The structure of the manifest would look like this:
```
meta: 
  title: "A Collection of Google Docs"
  authors:
    - name: Jenny Wilkerson
    - name: Jimmy Wolkerson
toc:
  - title: Introduction
    url: http://docs.google.com/introduction
  - title: Section 1
    url: http://docs.google.com/section-1
    starting_section: true
    children:
      - title: Section 1.a
        url: http://docs.google.com/section-1-a
      - title: Section 1.b
        url: http://docs.google.com/section-1-b
  - title: Section 2
    url: http://docs.google.com/section-2
```

The ingestion strategy would generate a table of contents based on that structure. A text section (rather than a text) would be created from each Google doc referenced in the manifest. Meta data would be stored in the `meta` section of the yaml. We'd stick with dublin tags for metadata, or some similar spec wherever possible. Ideally, we'd keep it close to the meta attributes we look for in EPUBs for simplicity.

## *Why* is this feature important? *Who* does it help?
This would allow a group with many discrete but related google docs to create a single publication out of them. We believe this could be a common use case among groups of scholars or at academic centers.

## Design Notes
We probably need to improve the ingestion flow generally and give it a design pass. Ideally, we'd be able to provide documentation and help text about this format during ingestion.

**Comment by zdavis** [comment] 2018-05-18 20:43
This is a duplicate of #1040

**Comment by zdavis** [comment] 2018-05-18 20:47
Maybe adjust this so it just focuses on the one use case of multiple google docs in one text?

It would pose some interesting problems for re-ingestion. It strikes me as a very focused used case (and one with an easy work around, which would be combining the docs into a single doc). I also wonder why it couldn't be multiple texts in one project, which would be the manifold way to accomplish this.

**Comment by mkgold** [comment] 2018-05-19 17:18
> and one with an easy work around, which would be combining the docs into a single doc

Agreed. If we can implement a TOC for Google docs, I think this is an acceptable workaround

> I also wonder why it couldn't be multiple texts in one project, which would be the manifold way to accomplish this.

This is one thing I think needs rethinking, in part because of the way we handle the "published" version of project. Am I right there can only be only one text that is "published"? That works fine for a book manuscript, but it doesn't fit this other use case at all, IMO

**Comment by zdavis** [comment] 2018-05-19 17:44
I don’t think that would be that hard to address. We could just allow the
project to specify a target for a start reading button, rather than assume
it’s the published text. Isn’t that all would be necessary to address this?
Then the user could categorize and group texts however she chose to.

**Comment by zdavis** [comment] 2018-05-19 18:29
Which is to say, I think the tight coupling between a text being
“published” and the “start reading” button appearing is a mistake we should
address. Our early thinking around this was too narrowly focused on press
use cases.

**Comment by mkgold** [comment] 2018-05-21 04:04
Okay -- I guess I was thinking about how the texts look on the project homepage rather than the functionality related to the "Start Reading" button. The way I understand it, in the list of texts, there is one "published" text and then everything else appears below that one in a separate section

**Comment by zdavis** [comment] 2018-05-21 14:37
Matt, do you still think the solution I'm proposing wouldn't work? It seems like a user who didn't set a text to published could still group separate texts in whatever way made the most sense. I'm still not sure why they _wouldn't_ set the Event Workbook as the published text for the project, but I'm sure I'm missing something.

**Comment by mkgold** [comment] 2018-05-21 17:05
I don't think the "published text" scenario is necessarily a good fit for the use case we are describing, where, say, twenty different google docs are added separately to a project. I guess that one could not set one of those texts to be published, but that doesn't feel like an intuitive solution to me.

So, maybe we should step back a bit and just think generally through the larger strategy around google doc ingestion. If we want the model to be that everything should be compiled into a single google doc, which would then be made the published version, I think we can do/advise people to do that. But having a TOC would be essential in that case, I'd think.

**Comment by zdavis** [comment] 2018-05-21 17:34
Sure, happy to talk it through—I think I'm having a hard time visualizing what the organizational needs for the 20 distinct texts scenario are, and how Manifold doesn't currently support them.

One thing we could do, Matt, would be to allow ingestion from a manifest that referenced a collection of Google docs. That doc would need to be something structured (json, XML, yaml, whatever), and it would need to express the structure of the text, probably in the form of a TOC, similar to how the summary.md file works with Markdown currently. Each item in that manifest would include a URL to a google doc, and Manifold could ingest each section. While a little more technical than a backend GUI—the user has to read our documentation and figure out how to make a manifest a text file that lists the google docs—it would fit nicely into our existing approach to ingestion, wouldn't require developing a bunch of new backend interfaces, and allow Manifold to meet the use case you describe. I'd be open to this approach, if you're convinced that the FI use case is a widespread case that other people would also want us to support.

**Comment by mkgold** [comment] 2018-05-21 18:06
that sounds like an interesting option to me! I think that most people could figure out YAML, especially if we gave them samples/templates/documentation

But moving in this direction wouldn't preclude the other option we've talked about in this thread, right? A single google doc compiled with all chapters, and a TOC produced from/with it?

**Comment by zdavis** [comment] 2018-05-21 18:08
The ability to include a TOC with a single google doc is already being addressed in a separate issue (#1040), and there's an open pull request that implements it. In other words, it's basically done at this point.

**Comment by mkgold** [comment] 2018-05-21 18:17
AWESOME

**Comment by SMaxOwok** [comment] 2018-05-21 18:21
Popping in again with another note: #1040 does _not_ address TOC generation for single page google doc.  I had started implementing this, but there was some discussion about the best way to approach that for google docs.  

Discussion starts around: https://manifold-community.slack.com/archives/C9TBE7AHF/p1526331879000345

**Comment by zdavis** [comment] 2018-05-21 18:36
Ok, this wasn't clear to me. Max, please do the following:

- Adjust #1040 so that it only speaks to HTML TOCs, which I think is all you're addressing in your PR.
- Open a new issue to cover google doc TOC (reference this one, and reference #1040 for context), and assign this issue to me.
- Make sure your commits or your PR reference #1040, so that it's clear. I didn't see a link from the issue to the PR, so there wasn't an easy way for me to know that it didn't address the entirety of the issue.

Thanks! Keeping the issue/PR relationships tight will make it easier for me to communicate clearly about what's done and not done on this project.

Sorry, Matt, for the misinformation. Let's continue conversation about TOCs for singular docs in a separate issue.  Are you OK with me adjusting this issue so that it is focused on the concept of ingesting multiple docs into a single text?

**Comment by zdavis** [comment] 2018-05-21 18:38
No worries — so many communication channels, it's hard to keep them all straight sometimes

**Comment by mkgold** [comment] 2018-05-22 14:07
> Are you OK with me adjusting this issue so that it is focused on the concept of ingesting multiple docs into a single text?

Yes, of course. Thanks so much to you and Max for your work on this.

**Comment by zdavis** [comment] 2018-05-22 14:53
@mkgold I've updated the issue text above. Let me know if you have any concerns about my changes. Thanks!

**Comment by mkgold** [comment] 2018-05-22 15:35
your changes look AWESOME, Zach. Thank you!!! I'm really excited about this.

**Closed** 2018-05-29 21:08 UTC
Labels: feature request, has pull request
