### ISSUE TITLE
Journals layout add background image "Upload a file" button just jumps up the page

### ISSUE THREAD

**Issue by jojokarlin** [ManifoldScholar/manifold#3399] opened 2022-07-06 21:22 UTC
We're playing around with JITP test journals and when we go to add a background image in Layout (tested in Chrome and Firefox), the "upload a file" link hops up the page. Drag and drop behaves as expected.

## Expected Behavior
You would expect Manifold to open your file finder.

## Steps to Reproduce
1. Enter Admin mode
2. In a Journal, navigate to Layout>Description+Images
3. in shelf, at "background image"
4. click "upload a file"

https://cuny.manifoldapp.org/backend/journals/af82626f-119f-484b-8665-bd8f358d39f1/layout

## Context (Environment)
In both Chrome and Firefox the "upload a file" jumps up the page rather than opening a window to browse files.

**Comment by zdavis** [comment] 2022-07-06 21:24
Could you share a screenshot?

**Comment by jojokarlin** [comment] 2022-07-06 21:39
![image-upload-gif](https://user-images.githubusercontent.com/9396684/177648024-aa28e373-f5a3-41d3-a99a-c18b1dbe8f07.gif)
Ok -- bizarrely, after I went through the process of downloading LICEcap to record a gif, it DID work. but then I exited admin mode, reentered admin mode and it didn't work again...

**Comment by zdavis** [comment] 2022-07-06 21:40
Hmmm.. I'm not able to reproduce, and I can't really see what the problem is in that screen capture.

**Comment by jojokarlin** [comment] 2022-07-06 21:46
If you click the link it just returns you to the top of the shelf. I'm not sure how better to describe it. Nor do I at all understand why recording it seemed to fix it momentarily. But now the recording isn't changing anything
![image-upload-gif](https://user-images.githubusercontent.com/9396684/177648969-8c49e0a7-ac59-4c48-9928-9cebaa4e6941.gif)
.

**Comment by zdavis** [comment] 2022-07-06 21:47
Oh, I get it. Sorry — I think I know what's causing this. @dananjohnson Could this be the same issue you fixed in the PC drawer?

**Comment by jojokarlin** [comment] 2022-07-06 21:48
It was pretty cool when LICEcap (worst named but also helpful new-to-me tool) fixed it. But alas, it stopped working again.

**Comment by dananjohnson** [comment] 2022-07-06 22:06
Oh probably. Lemme take a look.

**Comment by krosemichael** [comment] 2022-08-30 14:29
I am finding the same issue occurring in any shelf in which I have to scroll down. It jumps to the top when I click on any  action buttons or links  (i.e. "yes" for course in the reading group edit shelf, or to add an image in the description and images shelf in the layout tab), it brings me to the top of the page and does not record my selection. I tested it in Chrome and Safari and on two different computers. It works as expected on my phone. It also worked as expected on UMN's instance, so it may be CUNY-specific.

**Comment by zdavis** [comment] 2022-08-30 14:47
@1aurend please investigate this and see if you can reproduce.

**Closed** 2022-09-07 20:06 UTC
Labels: Type: Bug
