### ISSUE TITLE
Set published feature in list view

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1723] opened 2018-12-06 20:55 UTC
Presently the toggle for which feature is `Published` lives within the feature settings. Functionally it'd be easier if that were exposed and editable in the list view. And also that when one feature is toggled as published it untoggles any other so that it's not possible for a user to have more than one feature listed as publisher.

**Comment by zdavis** [comment] 2019-04-04 15:23
Closing this as a duplicate of #2105

**Closed by zdavis** 2019-04-04 15:23 UTC
Labels: feature
