### ISSUE TITLE
Frontend dropdown styles aren't right in Firefox.

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#439] opened 2017-07-14 21:32 UTC
![screen shot 2017-07-14 at 2 32 04 pm](https://user-images.githubusercontent.com/255909/28231634-521851ba-68a1-11e7-8b6f-ac3895b3cfe5.png)

**Comment by zdavis** [comment] 2017-07-14 21:33
Opposite of double rainbow is double dropdown arrow.

**Comment by SMaxOwok** [comment] 2017-07-17 16:07
Related / dupe of #432

**Closed** 2017-07-25 22:41 UTC
Labels: bug, has pull request
