### ISSUE TITLE
Top-level replies on resource comment threads are not indented.

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2988] opened 2021-04-21 17:14 UTC
UW is reporting that when users annotate a resource on the detail page, they aren't always appearing in chronological order. In [this example](https://uw.manifoldapp.org/projects/2021-teaching-learning-symposium/resource-collection/poster-session-1-2-00-2-45-p-m/resource/mentoring-affects), Jamal's comment is out of order. Perhaps it was merely edited and the new timestamp is showing here instead of the original? 

<img width="721" alt="comments" src="https://user-images.githubusercontent.com/25825222/115593704-75cd8a80-a29a-11eb-8f93-c392665ac589.png">

**Comment by zdavis** [comment] 2021-04-21 18:54
We can/should still be sorting by created_at rather than updated_at. We'll take a look.

**Comment by zdavis** [comment] 2021-04-21 18:55
Er, I misspoke. What I meant to say is that if the timestamp is an edited timestamp, we need to indicate that.

**Comment by zdavis** [comment] 2021-04-21 18:55
@bot bug

**Comment by zdavis** [comment] 2021-04-21 18:55
Thank you for taking the time to report this bug. We've reviewed the issue and agree that this should be fixed. We’re adding a “planned” label to indicate that we consider this bug as part of our current work plan.

_This was an automated message, but please don't hesitate to reply. Our team watches these issues closely and will respond as soon as we're able to!_

**Comment by zdavis** [comment] 2021-06-16 18:09
I think the actual issue here is not about sorting, which is correct. The issue is that in comment threads on resources, the first level of replies is not correctly indented.

**Closed** 2021-06-16 18:28 UTC
Labels: Priority: High, Status: In Progress, Status: Planned, Type: Bug
