### ISSUE TITLE
Add info about Manifold version somewhere in the Dashboard

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#1187] opened 2018-07-11 20:16 UTC
## Feature Description
Right now we don't indicate to Manifold admins what version of Manifold they are on. Perhaps we should include this info the footer?

## *Why* is this feature important? *Who* does it help?
so that admins (particularly of our hosted installs) know which version  of Manifold they are using

## User Stories
I am an admin of a Manifold hosted install and I hear that there is a cool feature coming in v2.0. I am wondering what version my install is running but I have no way of knowing that.

## Design Notes
where should the version number info appear?

**Comment by zdavis** [comment] 2018-12-06 21:48
This is a no-brainer, IMO. We should do it.

**Comment by zdavis** [comment] 2018-12-10 18:51
This is a duplicate of #1204 which includes this request, and more. We'll address this in #1204.

**Closed by zdavis** 2018-12-10 18:51 UTC
Labels: feature
