### ISSUE TITLE
Password reset emails take 10 minutes to arrive

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#1546] opened 2018-10-26 16:42 UTC
I'm finding that on the CUNY manifoldapp.org instance, password reset emails take a long time to arrive -- sometimes 10 minutes. I believe I have experienced this on other Manifold instances as well -- the Minnesota one, for instance.

this has become an issue for me when I am about to give a presentation and need to log in, but it just generally seems like password reset emails should go out more or less instantaneously. Can I ask the CIC team to do some testing?

All of the password reset messages I sent were going to gmail addresses.

**Comment by zdavis** [comment] 2018-10-26 16:48
Matt,

There's a "send test email" button in the email section of settings. Could you try this yourself a few times and see if this is consistently the case? I sent a few yesterday and could not reproduce your issue. I just tested it again, and it consistently takes under 2 minutes.

Manifold sends mail in a background queue, which is the correct architecture. The mail is sent through SendGrid, which is an enterprise email service. Once the email is triggered in Manifold, I'm seeing it show up in the sendgrid queue in about a minute. Once it's left sendgrid, it's in the recipient's email server's hands, and there's nothing we can do about it.

I'm not seeing an actionable issue here... 

Zach

**Comment by mkgold** [comment] 2018-10-27 17:40
I just experimented with this, and both the test email and password reset emails came within two minutes of being requested. So that is definitely better than I've seen before. I will keep experimenting at different times and from different networks, as I have experienced the long delays multiple times

**Comment by zdavis** [comment] 2018-10-29 18:59
I'm pretty much certain that insofar as there's a problem here, it's with an upstream provider (Sendgrid or the recipients SMTP server), and not something we can really fix. I'm closing this issue for now, as I don't see it as actionable—if you continue to see this problem, I'm happy to reopen and discuss further, just keep in mind that it's likely occurring on parts of the stack that are out of our control.

**Closed by zdavis** 2018-10-29 18:59 UTC
Labels: question, under discussion
