### ISSUE TITLE
Firefox shows router error (on all pages?)

### ISSUE THREAD

**Issue by naomiyaki** [ManifoldScholar/manifold#630] opened 2017-10-04 20:24 UTC
![pasted image at 2017_10_02 02_50 pm](https://user-images.githubusercontent.com/1628239/31197879-598a3412-a907-11e7-851e-9c3a6505f7a6.png)

**Comment by zdavis** [comment] 2017-10-05 00:41
Seems like an exact dupe of #621, which I fixed today.

**Closed by zdavis** 2017-10-05 00:41 UTC
Labels: bug
