### ISSUE TITLE
Resource Page Login Difficult to Read

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2517] opened 2020-01-02 16:34 UTC
When not logged in on the UMN instance, if you visit a resource page, the prompt to login to annotate the resource is not well distinguished from the background:

![resource-login](https://user-images.githubusercontent.com/25825222/71678621-37c9f180-2d4b-11ea-8c51-1bd833fd7e95.png)

**Comment by zdavis** [comment] 2020-01-02 16:36
Dupe of #2445. Fixed in master, will be fixed in next release.

**Closed by zdavis** 2020-01-02 16:36 UTC
