### ISSUE TITLE
Removing a "Text" that is linked to in a "Call-to-action" button results in 500 error for entire Project

### ISSUE THREAD

**Issue by caosborne89** [ManifoldScholar/manifold#2717] opened 2020-05-05 20:29 UTC
## Expected Behavior

After deleting a Text that was linked to a Call-to-action, I would expect the a Call-to-action button to be removed from public view, and maybe an alert displayed on the Call-to-action button on the admin side. Something indicating updating is needed. I would expect the project page to still viewable.

## Current Behavior

After deleting a Text that is linked to a  Call-to-action button, the "Link to text" field on the Call-to-action button form is set to "Select text" and when you try to do to the project page you get a 500 error.

## Possible Solution

See "Expected Behavior"
## Steps to Reproduce

1. Create a project
2. Add a "Text" to the project
3. Create a new "Call-to-action" button of type "Start Reading" and link new Text
4. Delete Text (from the Texts sub menu)

## Context (Environment)

If you have to re-add a text, you have to remember to update the Call-to-action button or else your entire project will not be viewable to users (500 error).

## Detailed Description

Proposing that error handling for Call-to-action buttons so that they don't crash the entire project page. Also suggesting that deleting a projects text does some updating to Call-to-action buttons.

**Comment by zdavis** [comment] 2020-05-05 20:41
Thanks for reporting this bug! However, this is a duplicate of #2667, which has been fixed. The fix will be in v5, which we expect to have a release candidate for later this week.

**Closed by zdavis** 2020-05-05 20:41 UTC

**Comment by caosborne89** [comment] 2020-05-05 20:44
Oops, apologies. I looked for duplicates and didn't make the connection to that one. Thanks for responding!

**Comment by zdavis** [comment] 2020-05-05 20:44
No worries—appreciate you taking the time to fill out the report!
