### ISSUE TITLE
Bulk Resource Import Throws Error at Useable CSV files

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1802] opened 2019-01-22 19:24 UTC
When loading [this resource log](https://github.com/ManifoldScholar/manifold/files/2784268/resource-log.csv.zip) (Drive ID: `1rAx3esu-2kgMYmRioY7hGyXJ1HImseQS`), the system will, inconsistently, throw the following error:

<img width="1161" alt="bulk" src="https://user-images.githubusercontent.com/25825222/51559877-baaeb080-1e48-11e9-8095-34586dc456ff.png">

After refreshing I'm able to load the file without issue and load the resources into the system successfully.

**Comment by zdavis** [comment] 2019-02-05 22:21
I'm not able to reproduce this with the information given. Closing for now, but happy to reopen and investigate further if you give me specific steps that I can use to reproduce this. I've uploaded the attached CSV file multiple times, and each time the importer is able to parse it. I believe you that this error was happening—I just can't figure out how to reproduce it.

**Closed by zdavis** 2019-02-05 22:21 UTC
Labels: bug, needs confirmation

**Comment by tsmyre** [comment] 2019-02-05 22:43
Curiously, it happened again to me today twice, on the UWI instance.

**Comment by zdavis** [comment] 2019-02-05 22:44
There's some state you're getting it into that I don't know how to reproduce. Can you try to figure out exactly how you get it there? I don't think it's random.

**Comment by tsmyre** [comment] 2019-02-05 22:52
The only behavior that stands out, but I couldn't reproduce it just now, is that I usually load an image resource manually, delete it, and then go to do a bulk upload.
