### ISSUE TITLE
Project detail page is returning 403 error

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#1744] opened 2018-12-16 18:39 UTC
I heard reports that a project URL was leading to an error message. I wasn’t able to duplicate until I tried from an iPhone.

Link: https://cuny.manifoldapp.org/projects/beyond-populism

When I access that on an iPhone, I reach a 403 error

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mkgold** [comment] 2018-12-16 19:32
Actually, I’m receiving reports of 403 errors on both laptop and mobile, but I haven’t verified myself

**Comment by SMaxOwok** [comment] 2018-12-17 15:44
```
W, [2018-12-17T15:42:43.580666 #27994]  WARN -- : [41e46f1b-ff72-4205-834c-48cd52160d21] #<#<Class:0x00007f85f624d690>:0x00007f85f6144dc0> is not authorized to read this resource: Beyond Populism
I, [2018-12-17T15:42:43.582060 #27994]  INFO -- : [41e46f1b-ff72-4205-834c-48cd52160d21] [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.16ms)
I, [2018-12-17T15:42:43.582404 #27994]  INFO -- : [41e46f1b-ff72-4205-834c-48cd52160d21] Completed 403 Forbidden in 59ms (Views: 1.0ms | ActiveRecord: 6.4ms)
```

**Comment by SMaxOwok** [comment] 2018-12-17 15:48
After looking closer, this is not a bug.  Project in question is marked as draft and thus only visible to editors, admins, etc.

**Closed by SMaxOwok** 2018-12-17 15:48 UTC
Labels: bug, confirmed
