### ISSUE TITLE
Missing margin in backend project detail form

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#370] opened 2017-06-02 15:40 UTC
![screen shot 2017-06-02 at 8 40 21 am](https://cloud.githubusercontent.com/assets/255909/26733275/24fa5064-476f-11e7-83c3-25ce546cf6b3.png)

**Comment by SMaxOwok** [comment] 2017-06-02 17:28
Duplicate of #369

**Closed** 2017-06-02 17:29 UTC
Labels: bug
