### ISSUE TITLE
Missing navbar in Chrome 84 on OSX 10.15.3

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2823] opened 2020-08-20 22:05 UTC
A user is reporting that the Manifold reader menu/nav bar is not rendering when viewed in Chrome 84 on OSX 10.15.3. The screenshot here demonstrates the behavior. And the text in question can be found [here](https://digitalpublications.brown.edu/read/first-readings-test/section/6ec74a9f-1711-4002-a531-b715ecc27da1).

<img width="1423" alt="nav" src="https://user-images.githubusercontent.com/25825222/90830420-3fa0cb00-e307-11ea-9ef6-8a14985dfa55.png">

**Comment by zdavis** [comment] 2020-08-20 22:07
We're unable to reproduce this. I'd like the user to disable any browser extensions, clear cache, reload, look at the developer console and try to get us more information if possible.

**Comment by cbrusch** [comment] 2020-09-02 19:02
Hi. I took all of these steps and discovered that this [Read Mode extension](https://chrome.google.com/webstore/detail/read-mode/nagcaahojecfeopbghgihcabgiepploa?hl=en#:~:text=Read%20Mode&text=Puts%20Google%20Chrome%20into%20read,removed%20while%20on%20read%2Dmode.) is causing the issue. Everything works fine once the extension is disabled.

I'm also attaching some screenshots from the dev console with the extension disabled and enabled (but inactive), if still needed. Thanks!

<img width="1394" alt="disabledReadMode" src="https://user-images.githubusercontent.com/22689711/92025176-277c7300-ed2d-11ea-9316-7f7926ebbe4a.png">
<img width="1394" alt="enabledReadMode" src="https://user-images.githubusercontent.com/22689711/92025201-2ea38100-ed2d-11ea-97e5-08d61cc53799.png">

**Comment by zdavis** [comment] 2020-10-09 23:04
Thanks for the update. I'm going to close this issue for now, but if more folks report problems around this we can always reopen.

**Closed by zdavis** 2020-10-09 23:04 UTC
Labels: Type: Bug
