### ISSUE TITLE
DS_Store Invalidates Manifest Archives

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2612] opened 2020-02-10 17:52 UTC
On the Minnesota instance I just reingested a Manifest Archive. The process failed on account of a validation exception. Manifold's error message indicated the file types it was expecting, but not which was flagging the error. I noticed I had a rogue DS Store file in my archive. After removal the reingest worked as expected. Given the prevalence of these to creep up when using hosting services like Google Drive, it would be useful if Manifold could ignore or simply remove the DS Store file(s) present in such uploads.

**Comment by zdavis** [comment] 2020-02-11 22:54
@bot bug

**Comment by zdavis** [comment] 2020-02-11 22:55
@bot bug

**Comment by zdavis** [comment] 2020-02-11 22:56
@bot bug

**Comment by zdavis** [comment] 2020-02-11 22:58
@bot bug

**Comment by zdavis** [comment] 2020-02-12 00:42
@bot bug

**Comment by zdavis** [comment] 2020-02-12 00:43
Thank you for taking the time to report this bug. We've reviewed the issue and agree that this should be fixed. We’re adding a “planned” label to indicate that we consider this bug as part of our current work plan.

_This was an automated message, but please don't hesitate to reply. Our team watches these issues closely and will respond as soon as we're able to!_

**Comment by zdavis** [comment] 2020-02-20 20:35
I'm unable to reproduce this problem. The attached archive contains a .DS_Store file in the root, and I'm able to successfully ingest it. 

Do you have a test source file I could use to reproduce this problem?

[ingest.zip](https://github.com/ManifoldScholar/manifold/files/4232868/ingest.zip)

**Comment by tsmyre** [comment] 2020-02-21 16:33
I was able to recreate on Edge just now. The log, included in full below, suggested that the ingest was complete but no text was actually ingested.

I've transmitted the archive I used via DM in Slack. 

```
Connecting to Manifold websocket...
Successfully connected to websocket.
Ingesting "80d3fbce7a8307efa2b4c9fb61acd25b.zip"
Using strategy Manifest
Converting source file "ump-emerson-draft-0007.html"
Converting source file "ump-emerson-draft-0004.html"
Converting source file "ump-emerson-draft-0008.html"
Converting source file "ump-emerson-draft-0005.html"
Converting source file "ump-emerson-draft-0006.html"
Converting source file "ump-emerson-draft-0003.html"
Converting source file "ump-emerson-draft-0002.html"
Converting source file "ump-emerson-draft-0001.html"
Created new text "1a93ef8a-b17e-41ed-a583-7ad18b85ef73"
Language is "en-US"
Rights are "Copyright 2020 by the Regents of the University of Minnesota"
Publication date is ""
Description is "Each chapter in this book thinks through one aspect of the extended laboratory model in order to better understand the place of hybrid labs in the academic and cultural spheres. This chapter in particular is about how labs produce and assign value to people, both internally and for the outside world. Labs are about social production and the production of social relations inside and outside the lab, as idealised humanism in some cases and as critical reflective practice in others. This chapter pays particular attention to the management techniques of people in Edison’s Menlo Park laboratory and the evolution of these techniques in the MIT Media lab which emerges in the 1980s and paves way for the mainstream form of understanding the North-American corporate innovation lab model through the 1990s and 2000s. In combination with lab discourse, such techniques create the conditions for the high visibility and empowerment of some while simultaneously rendering others invisible and disempowered. Our point is to read through these case studies and examples how people—and the missing people—are constantly produced in lab projects and discourses. While this chapter outlines how the focus on directors emerges from both existing lab cultures over the 20th century and the 1970s’ turn to managerialism, we are also interested in how this impacts the wider social context of the knowledge worker in the lab with repercussions for questions of gender, sexuality, and ethnicity including practices of racialization."
Created new Main title "Chapter 2: Lab Space"
Created new creator "Lori Emerson"
Created new creator "Jussi Parikka"
Created new creator "Darren Wershler"
Created new ingestion_source "ump-a11y.css"
Created new ingestion_source "images/ump-emerson-02-fig03.jpeg"
Created new ingestion_source "images/ump-emerson-02-fig06.jpeg"
Created new ingestion_source "images/ump-emerson-02-fig07.jpeg"
Created new ingestion_source "images/ump-emerson-02-fig13.jpeg"
Created new ingestion_source "images/ump-emerson-02-fig11.jpeg"
Created new ingestion_source "images/ump-emerson-02-fig05.jpeg"
Created new ingestion_source "images/ump-emerson-02-fig12.jpeg"
Created new ingestion_source "images/ump-emerson-02-fig10.jpeg"
Created new ingestion_source "images/ump-emerson-02-fig09.jpeg"
Processing failed.

Validation error: Validation failed: Attachment isn't of allowed format (allowed formats: gif, jpeg, jpg, png, svg, mp4, webm, flv, mov, avi, flac, mp3, wav, ogg, oga, xls, xlt, xlm, xlsx, xlsm, xltx, xltm, xlsb, xla, xlw, csv, ods, ots, doc, docx, docm, dotx, dotm, docb, odt, ott, txt, rtf, ppt, pptx, pptm, potx, potm, ppam, ppsx, ppsm, sldx, sldm, odp, otp, zip, md, epub, pls, ncx, dmg, mid, wma, wmv, tex, latex, pdf, tex, latex, js, xhtml, html, htm, ttf, otf, woff, css, xml, smil, yaml, yml)

Validation failed: Attachment isn't of allowed format (allowed formats: gif, jpeg, jpg, png, svg, mp4, webm, flv, mov, avi, flac, mp3, wav, ogg, oga, xls, xlt, xlm, xlsx, xlsm, xltx, xltm, xlsb, xla, xlw, csv, ods, ots, doc, docx, docm, dotx, dotm, docb, odt, ott, txt, rtf, ppt, pptx, pptm, potx, potm, ppam, ppsx, ppsm, sldx, sldm, odp, otp, zip, md, epub, pls, ncx, dmg, mid, wma, wmv, tex, latex, pdf, tex, latex, js, xhtml, html, htm, ttf, otf, woff, css, xml, smil, yaml, yml)
```

**Closed** 2020-02-21 18:45 UTC
Labels: Priority: High, Status: Clarification Needed, Status: Planned, Type: Bug
