### ISSUE TITLE
Is a Project Author permission not working

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#898] opened 2018-03-29 03:07 UTC
I assigned a dummy account (Reader role) author permissions to two projects on private staging and neither is showing the pink highlighting or underlining for annotations.

And I can't place resources either.

**Comment by zdavis** [comment] 2018-03-29 12:24
Duplicate of #899 I think. Closing in favor of that issue.

**Closed by zdavis** 2018-03-29 12:24 UTC
