### ISSUE TITLE
Unable to paginate project list in Firefox

### ISSUE THREAD

**Issue by jojokarlin** [ManifoldScholar/manifold#3398] opened 2022-07-06 18:22 UTC
When I attempt to add content on a private reading group by clicking "browse projects" (coming by way of the Reading Groups main menu button), I briefly get a 503 and then get redirected to the full project first page again. (https://cuny.manifoldapp.org/projects/all?standaloneModeEnforced=false)

## Expected Behavior
Manifold should add the content to the Reading Group page

## Current Behavior
Page returns to first page of projects and when I navigate back to the reading group, I still see the "Ready to start customizing" prompts.

## Steps to Reproduce

1. click "Reading Groups" on top menu
2. click "My Groups"
3. select a group that doesn't yet have content
4. click "Browse projects"
5. try to page forward to browse projects

**Comment by zdavis** [comment] 2022-07-06 19:12
I'm not able to reproduce this. Is this happening in all browsers?

**Comment by jojokarlin** [comment] 2022-07-06 19:35
I was in Firefox, but it seems fine in Chrome.

**Comment by zdavis** [comment] 2022-07-06 19:37
@bot bug

**Comment by zdavis** [comment] 2022-07-06 19:37
Thank you for taking the time to report this bug. We've reviewed the issue and agree that this should be fixed. We’re adding a “planned” label to indicate that we consider this bug as part of our current work plan.

_This was an automated message, but please don't hesitate to reply. Our team watches these issues closely and will respond as soon as we're able to!_

**Comment by zdavis** [comment] 2022-07-06 19:39
Updated issue title to more accurately represent the problem.

**Closed** 2022-07-12 16:15 UTC
Labels: Type: Bug, Status: Planned, Priority: High
