### ISSUE TITLE
Annotation locations are not stable in reingested texts

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#1010] opened 2018-04-26 20:26 UTC
So I did a quick test of what happens when a text is reingested where the source document has been altered such that annotations, etc. can't be reanchored. I had two annotations in spaces that I wasn’t going to adjust in any way. Between them I had a paragraph I was going to delete. I annotated every sentence in that soon-to-be-deleted paragraph with one marked as Private and one that spanned from that paragraph to the next. I even threw in a highlight. Then I deleted the para. in the source document and reingested it. The listings from the `Your Notes` dropdown after reingestion lists everything as if nothing had happened. But, in addition to not being able to get an action from clicking on those listings from the para. that was deleted, the one that followed after in a safe spot was also not clickable.

I did all this using the HTML ingestion strategy.

**Comment by zdavis** [comment] 2018-05-08 18:16
Max, I'm assigning this to you for now.

In theory, the IDs of each text node is created based on the contents of the node. Ideally, nodes that don't change between ingestions remain stable, which would keep the placement of most annotations intact when a text is re-ingested. Terence is reporting this is not in fact what's happening, so we need to get to the bottom of this.

These IDs are generated within the Serializer:Html class. I'd start by looking at this commit:

https://github.com/ManifoldScholar/manifold/commit/cb0c40a61bb1a37baf327dac133966095edb5997

That is where I attempted to introduce some stability. I added a few quick specs there, but they don't really prove that the IDs are stable. You should be able to reproduce Terence's issue via new specs. Let me know if you want to discuss.

Zach

**Comment by zdavis** [comment] 2018-05-15 22:05
@tsmyre I'm going to accept a pull request that will address some parts of this issue, but not others. In a nut shell, here's the behavior this PR will introduce:

1. When a text section changes, Manifold will check every annotation on that text section to see whether it is orphaned as a result of the change. Orphaned annotations are annotations with a start or end node that no longer exists in the text section.

2. If the annotation is orphaned, Manifold will attempt to adopt it. That means that Manifold will search through the text nodes in the section and look for text that exactly matches whatever the user annotated. If there is more than one match, it means that Manifold can't figure out where the annotation goes with 100% certainty. If Manifold isn't sure where it goes, it won't try to place it.

3. We're updating places where annotations are listed to exclude orphaned annotations. In the future, we could make an interface for listing or even placing orphaned annotations.

There will still be cases where the annotation can be orphaned, and I think that's a feature, not a bug. For example, imagine three consecutive paragraphs (A, B, and C), and an annotation that begins in paragraph A and ends in C. If an editor removes paragraph B, it means that the text that was originally highlighted has fundamentally changed. In that case, is it correct to persist the annotation? What if the meaning changed in some way that makes the Annotation irrelevant?

We might want to do more thinking around this, but I'd want to wait for more info from our users before spending a lot more time here.

**Closed** 2018-05-15 22:13 UTC
Labels: bug, has pull request

**Comment by mkgold** [comment] 2018-05-16 14:14
also, who gets to choose where the annotation should go -- the annotator or the author/editor?

**Comment by zdavis** [comment] 2018-05-16 14:15
I think it would be the annotator.
