### ISSUE TITLE
Allow bulk upload to map Sort Title field

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2881] opened 2020-11-16 23:05 UTC
The `Sort Title` attribute is not presently one that can be mapped during a resource bulk upload. If possible, it would be good to make available to bulk upload all fields available in the system to any resource.

**Comment by zdavis** [comment] 2021-04-07 21:59
Duplicate of #2943

**Closed** 2021-04-07 22:17 UTC
Labels: Type: Bug
