### ISSUE TITLE
Manifold epub ingestion errors should be more obvious.

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#794] opened 2018-02-12 20:49 UTC
I tried to upload an ePub, and it did not seem to take; I've shared the file with Zach. And, while I'm sure it is a problem with the ePub, what happened when it failed to load was that the Texts screen basically reloaded, without an error message. It would be good if Manifold could throw some kind of error message upon a failed upload.

**Comment by zdavis** [comment] 2018-02-13 15:55
I'm not able to reproduce the behavior you describe. When I ingest this text (in the same version that you were using yesterday), the ingestion process shows the error that caused the failure:

![image](https://user-images.githubusercontent.com/255909/36159260-243b94ba-1093-11e8-9799-b99110f03333.png)

We could probably make this more apparent, but I think that's something we'd want to tackle as part of a larger redesign of the ingestion UX (which I think we'll want to tackle as part of a larger unit of work in which we introduce more ingestion options.

**Comment by zdavis** [comment] 2018-02-15 15:18
Hey @mkgold I'm going to close this issue unless you can give me more info, as I'm unable to reproduce the problem you describe. If you can't reproduce, we can always reopen if this pops up again for you.

**Comment by zdavis** [comment] 2018-03-13 23:18
Unable to reproduce. Closing.

**Comment by mkgold** [comment] 2018-03-16 00:52
Hi Zach -- I'm sorry, but I missed the notification you left [here](https://github.com/ManifoldScholar/manifold/issues/794#issuecomment-365958490)

I guess my question, from a UX perspective, is whether there should be some other kind of notification outside of the processing window that the ingest has failed. If you read through the terminal lines, yes, it shows that the process failed; but it's odd to me that if the process fails, the button below it still says "complete" with a green checkmark.

Maybe that's not something we can address easily, but for me it is a bit of a UX issue to consider.

**Comment by zdavis** [comment] 2018-03-16 00:53
At some point I'd like to circle back and do a larger design pass at the ingestion UI. But yes, I agree that we can surface the error better. I'll reopen.

**Comment by mkgold** [comment] 2018-03-16 00:56
thanks!

**Comment by SMaxOwok** [comment] 2018-11-20 17:36
@zdavis it seems like as titled this has been completed.  Thoughts?

**Comment by zdavis** [comment] 2019-02-15 17:19
I think this is still an issue, and am going to try to fix it RIGHT NOW. Relabeling this as a bug rather than a feature.

**Comment by zdavis** [comment] 2019-03-01 23:50
Fixed this son of a gun in 07f58b3e1438f56e0803d8a02b77a18baf61777b. CLOSING FOREVER.

**Closed by zdavis** 2019-03-01 23:50 UTC
Labels: bug
