### ISSUE TITLE
Serializer error after doing something (?) in the Rich Text Editor (8.0 beta-2.1)

### ISSUE THREAD

**Issue by tefkah** [ManifoldScholar/manifold#3674] opened 2023-10-20 10:41 UTC
I was editing a text, when suddenly this error appeared, and I was no longer able to access this section.
All other sections were fine.

I can't remember exactly what I did unfortunately, so cannot help there. If there's any way for me to provide more concrete logs/more info i'm happy to help!

<img width="931" alt="image" src="https://github.com/ManifoldScholar/manifold/assets/21983833/04799030-0dc2-443c-beeb-d203cc36ace0">

**Comment by 1aurend** [comment] 2023-10-23 20:52
@tefkah are you able to share the `body` and `bodyJSON` data for the section? (It'll be an html string and JSON respectively.) If the text is public, we can grab it from the Manifold URL, or if not, you could hit the text api endpoint and share the response.

**Comment by tefkah** [comment] 2023-10-31 15:35
Hi @1aurend, unfortunately I've removed the offending pages and can't reliably reproduce this problem. I will send you this as soon as I can reproduce it!

**Comment by 1aurend** [comment] 2023-10-31 19:17
Sounds good. Thanks @tefkah! Fwiw, I also tried to reproduce this by setting a text section body to several variations of invalid html, and I couldn't reproduce it either. I did add error handling that should now route you to the html editor when you open the section if the body can't be parsed for the RTE. Hopefully, that will at least provide a way to fix the issue if this happens again.

**Comment by zdavis** [comment] 2023-11-29 17:42
Unable to reproduce. Closing. Feel free to reopen if this pops up again.

**Closed by zdavis** 2023-11-29 17:42 UTC
